spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 94.191.121.218:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080

server:
  port: 8780

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true