spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 94.191.121.218:8848

server:
  port: 8680

management:
  endpoints:
    web:
      exposure:
        include: "*"